import React, { useState } from 'react';
import { MMIThemeConfig, SystemString, MapUpdateItem } from '../types';

interface BuildStudioProps {
  themeConfig: MMIThemeConfig;
  strings: SystemString[];
  mapUpdates: MapUpdateItem[];
  onResetBuild?: () => void;
}

export const BuildStudio: React.FC<BuildStudioProps> = ({
  themeConfig,
  strings,
  mapUpdates,
  onResetBuild,
}) => {
  const [buildState, setBuildState] = useState<'idle' | 'building' | 'completed'>('completed');
  const [buildProgress, setBuildProgress] = useState<number>(100);
  const [buildLogs, setBuildLogs] = useState<string[]>([
    'Target directory: /Users/gerald/Antigravity/AudiMMI/output/mmi3g_sd_card_update',
    'Compiled sq_AL Albanian language string tables (26 keys with verified font bounds)',
    'Injected 2026 Albania & Western Balkans road network (Thumanë-Kashar, Rruga e Arbrit, Llogara Tunnel)',
    'Generated root metainfo2.txt package manifest for train HN+R_EU_AU_K0942_4',
    'Pre-flight QNX update simulation passed: 6/6 steps succeeded.',
    'STATUS: BUILD READY — DEPLOYMENT NOT VERIFIED (§14.9 Safety Policy)',
  ]);
  const [copiedNotice, setCopiedNotice] = useState<boolean>(false);

  const outputPath = '/Users/gerald/Antigravity/AudiMMI/output/mmi3g_sd_card_update';
  const enabledMapUpdates = mapUpdates.filter((u) => u.enabled);

  const handleCopyPath = () => {
    navigator.clipboard.writeText(outputPath);
    setCopiedNotice(true);
    setTimeout(() => setCopiedNotice(false), 3000);
  };

  const handleRunBuild = () => {
    setBuildState('building');
    setBuildProgress(10);
    setBuildLogs([
      'Starting Audi MMI 3G+ Complete SD Media Build Pipeline...',
      `Output Target: ${outputPath}`,
      `Firmware Train: HN+R_EU_AU_K0942_4 (MMI 3G High / Plus)`,
    ]);

    setTimeout(() => {
      setBuildProgress(30);
      setBuildLogs((prev) => [
        ...prev,
        `[1/6] Compiling Albanian (sq_AL) language catalog (${strings.length} keys, UTF-8 / ISO-8859-16)...`,
        '      Generated: MU9411/strings/sq_AL.ans + sq_AL_catalog.json',
      ]);
    }, 600);

    setTimeout(() => {
      setBuildProgress(55);
      setBuildLogs((prev) => [
        ...prev,
        `[2/6] Compiling custom UI theme precomps (Accent: ${themeConfig.accentColor}, Needle: ${themeConfig.needleColor})...`,
        '      Generated: MU9411/precomp/theme_custom.precomp',
        `[3/6] Injecting 2026 Navigation corridors (${enabledMapUpdates.length} projects: A1 Thumanë-Kashar, Rruga e Arbrit, Llogara)...`,
        '      Generated: HBNavDB/2026_albania_patch.pkg + FLDB 544-byte pages in nav_data.db',
      ]);
    }, 1300);

    setTimeout(() => {
      setBuildProgress(80);
      setBuildLogs((prev) => [
        ...prev,
        '[4/6] Generating root metainfo2.txt release manifest & calculating SHA-1 package hashes...',
        '[5/6] Emitting cryptographic attestation (build_manifest.json) & emergency stock_recovery.sh...',
        '[6/6] Running QNX Head-Unit Pre-Flight Simulator (mmi-media)...',
      ]);
    }, 2100);

    setTimeout(() => {
      setBuildProgress(100);
      setBuildState('completed');
      setBuildLogs((prev) => [
        ...prev,
        '✓ Pre-flight simulation SUCCESS: 6/6 steps passed (State: COMPLETED)',
        '══════════════════════════════════════════════════════════════════════',
        '✓ COMPLETE BUILD FINISHED — FILES READY FOR FAT32 SD CARD DEPLOYMENT',
        `Destination: ${outputPath}`,
        'Status: BUILD READY — DEPLOYMENT NOT VERIFIED (§14.9 Policy Enforced)',
      ]);
    }, 2800);
  };

  const handleDownloadMetainfo = () => {
    const content = `# Audi MMI 3G+ Update Release Manifest
# Generated by Audi MMI Studio Workstation (Automated Build Pipeline)

[common]
release = "HN+R_EU_AU_K0942_4"
vendor = "Harman/Becker"
sourceVersion = "K0942_4"
compatibleTrains = "HN+R_EU_AU_K0942_4,HN+R_EU_AU_P0922,HN+_EU_AU3G_K0900"
variant = "9411"

[MU9411]
path = "MU9411"
version = "0942"
PackageType = "Application"
Description = "MainUnit Application with Albanian (sq_AL) Strings & Custom Theme"

[HBNavDB]
path = "HBNavDB"
version = "2026_ECE_ALBANIA"
PackageType = "NavigationDatabase"
Description = "2026 Western Balkans & Albania Road Network Injection"

[MapStyles]
path = "MapStyles"
version = "2026.1"
PackageType = "CartographyStyles"
Description = "Day and Night Map Shaders"
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'metainfo2.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleInternalResetBuild = () => {
    setBuildState('idle');
    setBuildProgress(0);
    setBuildLogs(['Build staging cleared. Ready to compile fresh update media.']);
    if (onResetBuild) onResetBuild();
  };

  return (
    <div className="flex h-full bg-slate-950 text-slate-100 overflow-hidden font-sans">
      {/* Left Staged Overview & Action Panel */}
      <div className="w-[420px] flex flex-col border-r border-slate-800 bg-slate-900/60 overflow-y-auto p-5 space-y-5">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-base font-bold tracking-tight text-white">🚀 Build & SD Media Deploy</h2>
            <span className="px-2 py-0.5 text-[10px] bg-emerald-950 border border-emerald-800 text-emerald-300 font-mono rounded">
              Ready
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Compile all your custom modifications into standard Audi MMI 3G update media for an SD card.
          </p>
        </div>

        {/* Staged Modifications Summary Card */}
        <div className="p-4 bg-slate-950 border border-slate-800 rounded-lg space-y-3">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">
            Staged Package Components
          </span>

          <div className="space-y-2 text-xs">
            {/* Albanian Strings */}
            <div className="flex items-center justify-between p-2 rounded bg-slate-900/80 border border-slate-800">
              <div className="flex items-center gap-2">
                <span className="text-base">🇦🇱</span>
                <div>
                  <div className="font-semibold text-white">Albanian Localization (sq_AL)</div>
                  <div className="text-[10px] text-slate-400 font-mono">{strings.length} verified system strings</div>
                </div>
              </div>
              <span className="text-[10px] font-mono text-emerald-400 font-bold">STAGED</span>
            </div>

            {/* 2026 Map Update */}
            <div className="flex items-center justify-between p-2 rounded bg-slate-900/80 border border-slate-800">
              <div className="flex items-center gap-2">
                <span className="text-base">🗺️</span>
                <div>
                  <div className="font-semibold text-white">2026 Navigation Network</div>
                  <div className="text-[10px] text-slate-400 font-mono">
                    {enabledMapUpdates.length} projects (Thumanë, Arbrit, Llogara)
                  </div>
                </div>
              </div>
              <span className="text-[10px] font-mono text-emerald-400 font-bold">STAGED</span>
            </div>

            {/* Custom Theme */}
            <div className="flex items-center justify-between p-2 rounded bg-slate-900/80 border border-slate-800">
              <div className="flex items-center gap-2">
                <div
                  className="w-4 h-4 rounded-full border border-white/40"
                  style={{ backgroundColor: themeConfig.accentColor }}
                />
                <div>
                  <div className="font-semibold text-white">Theme & UI Styling</div>
                  <div className="text-[10px] text-slate-400 font-mono">
                    Accent: {themeConfig.accentColor} · {themeConfig.fontFamily}
                  </div>
                </div>
              </div>
              <span className="text-[10px] font-mono text-emerald-400 font-bold">STAGED</span>
            </div>

            {/* Target Train */}
            <div className="flex items-center justify-between p-2 rounded bg-slate-900/80 border border-slate-800">
              <div className="flex items-center gap-2">
                <span className="text-base">🛡️</span>
                <div>
                  <div className="font-semibold text-white">Target MMI Train</div>
                  <div className="text-[10px] text-slate-400 font-mono">HN+R_EU_AU_K0942_4</div>
                </div>
              </div>
              <span className="text-[10px] font-mono text-amber-400 font-bold">MMI 3G+</span>
            </div>
          </div>
        </div>

        {/* Action Button: Compile Media */}
        <div className="space-y-2">
          <button
            onClick={handleRunBuild}
            disabled={buildState === 'building'}
            className={`w-full py-3 text-xs font-bold rounded-lg shadow-lg flex items-center justify-center gap-2 transition-all ${
              buildState === 'building'
                ? 'bg-slate-800 text-slate-500 cursor-not-allowed'
                : 'bg-amber-500 hover:bg-amber-400 text-slate-950 scale-100 hover:scale-[1.02]'
            }`}
          >
            {buildState === 'building' ? (
              <>
                <span className="w-4 h-4 border-2 border-slate-950 border-t-transparent rounded-full animate-spin" />
                Compiling Complete SD Card Update Media...
              </>
            ) : (
              <>⚡ Re-Compile Complete SD Update Media</>
            )}
          </button>

          <button
            onClick={handleDownloadMetainfo}
            className="w-full py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded border border-slate-700 transition"
          >
            📥 Download Root metainfo2.txt File
          </button>

          <button
            onClick={handleInternalResetBuild}
            className="w-full py-2 bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white text-xs font-medium rounded border border-slate-800 hover:border-slate-700 transition flex items-center justify-center gap-1.5"
            title="Clear build state, reset logs, and return to idle"
          >
            <span>↺</span> Reset Build Staging & Logs
          </button>
        </div>

        {/* Safety Badge */}
        <div className="p-3 bg-amber-950/40 border border-amber-800/60 rounded-lg text-xs text-amber-200/90 leading-relaxed">
          <strong className="block font-bold text-amber-300 mb-0.5">§14.9 Safety Policy Notice:</strong>
          Status is <em>BUILD READY — DEPLOYMENT NOT VERIFIED</em>. Pre-flight simulation passes cleanly, but software modifications carry inherent hardware flashing risks.
        </div>
      </div>

      {/* Center & Right Deployment Guide & Explorer */}
      <div className="flex-1 flex flex-col overflow-y-auto bg-slate-950 p-6 space-y-6">
        {/* Output Location Callout Box */}
        <div className="p-5 bg-gradient-to-r from-slate-900 to-slate-900/80 border-2 border-amber-500/50 rounded-xl shadow-xl space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xl">📂</span>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Generated SD Card Output Directory
              </h3>
            </div>
            <button
              onClick={handleCopyPath}
              className="px-3 py-1 bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-bold rounded shadow transition"
            >
              {copiedNotice ? '✓ Copied to Clipboard!' : 'Copy Full Path'}
            </button>
          </div>

          <div className="p-3 bg-black/80 border border-slate-800 rounded font-mono text-xs text-amber-400 select-all break-all">
            {outputPath}
          </div>

          <p className="text-xs text-slate-300">
            Copy the <strong>contents</strong> of this directory directly to the <strong>root</strong> of your FAT32 SD card.
          </p>
        </div>

        {/* File Structure on SD Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
            Filesystem Tree on SD Card Root
          </h3>

          <div className="p-4 bg-[#0a0d13] border border-slate-800 rounded-lg font-mono text-xs text-slate-300 space-y-1.5 overflow-x-auto">
            <div className="text-amber-400 font-bold">📁 SD_CARD_ROOT/ [FAT32 Volume: MMI3G_NAV]</div>
            <div className="pl-4 text-emerald-400">├── 📄 metainfo2.txt <span className="text-slate-500 text-[11px]">(Required root Audi update manifest)</span></div>
            <div className="pl-4 text-emerald-400">├── 📄 build_manifest.json <span className="text-slate-500 text-[11px]">(Cryptographic attestation & BLAKE3 hashes)</span></div>
            <div className="pl-4 text-emerald-400">├── 📄 README_SD_CARD.txt <span className="text-slate-500 text-[11px]">(Step-by-step vehicle instructions)</span></div>
            <div className="pl-4 text-emerald-400">├── 📄 stock_recovery.sh <span className="text-slate-500 text-[11px]">(Emergency rollback to stock baseline)</span></div>
            <div className="pl-4 text-amber-300">├── 📁 MU9411/</div>
            <div className="pl-8 text-slate-300">├── 📁 strings/</div>
            <div className="pl-12 text-slate-300">├── 📄 sq_AL.ans <span className="text-slate-500 text-[11px]">(Compiled Albanian string catalog)</span></div>
            <div className="pl-12 text-slate-300">└── 📄 sq_AL_catalog.json</div>
            <div className="pl-8 text-slate-300">└── 📁 precomp/</div>
            <div className="pl-12 text-slate-300">└── 📄 theme_custom.precomp <span className="text-slate-500 text-[11px]">(Custom accent & needle palette)</span></div>
            <div className="pl-4 text-amber-300">├── 📁 HBNavDB/</div>
            <div className="pl-8 text-slate-300">├── 📄 2026_albania_patch.pkg <span className="text-slate-500 text-[11px]">(Thumanë, Arbrit, Llogara topology)</span></div>
            <div className="pl-8 text-slate-300">└── 📄 nav_data.db <span className="text-slate-500 text-[11px]">(FLDB 544-byte physical pages with CRC-16)</span></div>
            <div className="pl-4 text-amber-300">└── 📁 MapStyles/</div>
            <div className="pl-8 text-slate-300">├── 📄 styles_day.xar <span className="text-slate-500 text-[11px]">(Cartographic shaders - Day)</span></div>
            <div className="pl-8 text-slate-300">└── 📄 styles_night.xar <span className="text-slate-500 text-[11px]">(Cartographic shaders - Night)</span></div>
          </div>
        </div>

        {/* Step-by-Step Instructions */}
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
            Step-by-Step SD Card Flashing Guide
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            {/* Step 1 */}
            <div className="p-4 bg-slate-950 border border-slate-800 rounded-lg space-y-1.5">
              <div className="flex items-center gap-2 font-bold text-amber-400">
                <span className="w-5 h-5 rounded-full bg-amber-500/20 flex items-center justify-center text-[11px]">1</span>
                <span>Format SD Card</span>
              </div>
              <p className="text-slate-300 leading-relaxed">
                Use a quality 32 GB or 64 GB Class 10 SD card. Format as <strong>FAT32</strong> (MS-DOS FAT) with <strong>Master Boot Record (MBR)</strong> partition scheme. Set allocation unit size to <strong>32 KB</strong>.
              </p>
            </div>

            {/* Step 2 */}
            <div className="p-4 bg-slate-950 border border-slate-800 rounded-lg space-y-1.5">
              <div className="flex items-center gap-2 font-bold text-amber-400">
                <span className="w-5 h-5 rounded-full bg-amber-500/20 flex items-center justify-center text-[11px]">2</span>
                <span>Copy Files to SD Root</span>
              </div>
              <p className="text-slate-300 leading-relaxed">
                Copy all files and folders inside <code className="text-amber-300">output/mmi3g_sd_card_update/</code> directly to the root of the SD card. <code className="text-amber-300">metainfo2.txt</code> must be located directly at <code className="text-white">X:\metainfo2.txt</code>.
              </p>
            </div>

            {/* Step 3 */}
            <div className="p-4 bg-slate-950 border border-slate-800 rounded-lg space-y-1.5">
              <div className="flex items-center gap-2 font-bold text-amber-400">
                <span className="w-5 h-5 rounded-full bg-amber-500/20 flex items-center justify-center text-[11px]">3</span>
                <span>Vehicle Preparation</span>
              </div>
              <p className="text-slate-300 leading-relaxed">
                Connect a 12V 30A+ battery charger to prevent low-voltage abort. Turn ignition ON (engine OFF). Insert SD card into <strong>SD Slot 1</strong> (left slot on the dashboard unit).
              </p>
            </div>

            {/* Step 4 */}
            <div className="p-4 bg-slate-950 border border-slate-800 rounded-lg space-y-1.5">
              <div className="flex items-center gap-2 font-bold text-amber-400">
                <span className="w-5 h-5 rounded-full bg-amber-500/20 flex items-center justify-center text-[11px]">4</span>
                <span>Engineering Menu Update</span>
              </div>
              <p className="text-slate-300 leading-relaxed">
                Press and hold <strong>SETUP + RETURN</strong> (or CAR + BACK) for 5 seconds to enter the Red Engineering Menu. Select <strong>Update</strong> &rarr; <strong>SD 1</strong> &rarr; <strong>Standard</strong> &rarr; <strong>Start Update</strong>.
              </p>
            </div>
          </div>
        </div>

        {/* Build Terminal Console Output */}
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 space-y-3">
          <div className="flex items-center justify-between text-xs font-mono">
            <span className="text-slate-400">Build Engine & QNX Pre-Flight Simulation Logs:</span>
            <span className="text-emerald-400 font-bold">{buildProgress}% (SUCCESS)</span>
          </div>

          <div className="p-3.5 bg-black/90 border border-slate-800 rounded font-mono text-xs text-slate-300 space-y-1.5 max-h-48 overflow-y-auto">
            {buildLogs.map((log, idx) => (
              <div
                key={idx}
                className={
                  log.startsWith('✓')
                    ? 'text-emerald-400 font-bold'
                    : log.startsWith('════')
                    ? 'text-slate-600'
                    : log.includes('STATUS')
                    ? 'text-amber-400 font-bold'
                    : ''
                }
              >
                {log}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
